# Generated by Django 5.0 on 2023-12-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='albumID',
            new_name='albumId',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='thumbnailURL',
            new_name='thumbnailUrl',
        ),
    ]
